# Generated by Django 5.2.15 on 2026-06-25 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_phone_number', models.CharField(db_index=True, help_text='WhatsApp phone number of the user', max_length=20, unique=True)),
                ('current_state', models.CharField(default='MENU', help_text='Current state of the conversation', max_length=50)),
                ('session_data', models.JSONField(default=dict, help_text='Additional session data')),
                ('last_interaction', models.DateTimeField(auto_now=True, help_text='Timestamp of last interaction')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when session was created')),
            ],
            options={
                'verbose_name': 'WhatsApp Session',
                'verbose_name_plural': 'WhatsApp Sessions',
                'ordering': ['-last_interaction'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppWebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webhook_id', models.CharField(help_text='Unique ID for the webhook request', max_length=50, unique=True)),
                ('payload', models.JSONField(help_text='Full webhook payload')),
                ('processed', models.BooleanField(default=False, help_text='Whether the webhook was processed')),
                ('error_message', models.TextField(blank=True, help_text='Error message if processing failed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when webhook was received')),
            ],
            options={
                'verbose_name': 'Webhook Log',
                'verbose_name_plural': 'Webhook Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(editable=False, help_text='Unique reference number for the donation', max_length=30, unique=True)),
                ('whatsapp_phone_number', models.CharField(db_index=True, help_text='WhatsApp phone number of the donor', max_length=20)),
                ('cause', models.CharField(choices=[('FOOD', '🍲 Food Donation'), ('EDUCATION', '📚 Education Support'), ('MEDICAL', '🏥 Medical Assistance'), ('ORPHANAGE', '🏡 Orphanage Support'), ('ANIMAL', '🐾 Animal Welfare'), ('ENVIRONMENTAL', '🌿 Environmental Projects')], help_text='Selected donation cause', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Donation amount in INR', max_digits=10)),
                ('full_name', models.CharField(help_text='Full name of the donor', max_length=100)),
                ('mobile_number', models.CharField(help_text='Mobile number of the donor', max_length=15)),
                ('email', models.EmailField(help_text='Email address of the donor', max_length=254)),
                ('message', models.TextField(blank=True, help_text='Optional message from the donor', null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('UPI', 'UPI'), ('RAZORPAY', 'Razorpay'), ('BANK_TRANSFER', 'Bank Transfer')], help_text='Selected payment method', max_length=20, null=True)),
                ('payment_status', models.CharField(choices=[('PENDING', '⏳ Pending'), ('COMPLETED', '✅ Completed'), ('FAILED', '❌ Failed'), ('REFUNDED', '🔄 Refunded')], default='PENDING', help_text='Current payment status', max_length=20)),
                ('payment_id', models.CharField(blank=True, help_text='Payment gateway transaction ID', max_length=100, null=True)),
                ('payment_response', models.JSONField(blank=True, help_text='Full payment gateway response', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when donation was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when donation was last updated')),
            ],
            options={
                'verbose_name': 'Donation',
                'verbose_name_plural': 'Donations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['reference_number'], name='whatsapp_ap_referen_348475_idx'), models.Index(fields=['whatsapp_phone_number'], name='whatsapp_ap_whatsap_885e69_idx'), models.Index(fields=['payment_status'], name='whatsapp_ap_payment_19a492_idx'), models.Index(fields=['created_at'], name='whatsapp_ap_created_a943ad_idx')],
            },
        ),
    ]
