# Generated by Django 5.0.6 on 2024-05-24 12:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappsession',
            name='last_interaction',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp of the last user interaction'),
        ),
        migrations.AddField(
            model_name='whatsappsession',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]