# Generated by Django 5.2.14 on 2026-06-27 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_app', '0002_fooditem_package_patient_student_donation_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='image_url',
            field=models.URLField(blank=True, help_text='Public URL of the package image', max_length=500, null=True),
        ),
    ]
