# Generated by Django 5.2.14 on 2026-06-30 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_app', '0004_conversationmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappsession',
            name='language',
            field=models.CharField(default='en', help_text="Language code for the session (e.g., 'en', 'ta')", max_length=10),
        ),
    ]
