# Generated by Django 5.2.14 on 2026-07-01 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_app', '0005_whatsappsession_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappsession',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether the session is active'),
        ),
        migrations.AddField(
            model_name='whatsappsession',
            name='reminder_sent',
            field=models.BooleanField(default=False, help_text='Whether an idle reminder has been sent'),
        ),
    ]
