# Generated by Django 5.2.14 on 2026-07-01 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_app', '0002_whatsappsession_last_interaction_and_more'),
        ('whatsapp_app', '0006_whatsappsession_is_active_and_more'),
    ]

    operations = [
    ]
