# Generated by Django 5.0.6 on 2024-07-04 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_app', '0007_merge_20260701_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='easebuzz_access_key',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='easebuzz_txnid',
        ),
    ]