# Generated by Django 5.2.15 on 2026-06-26 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the food item (e.g. 'Feed a Homeless Person')", max_length=100)),
                ('price_per_unit', models.DecimalField(decimal_places=2, help_text='Price per unit in INR', max_digits=10)),
                ('unit_label', models.CharField(default='Person', help_text='Unit label (e.g. Person, Bottle, Plate)', max_length=30)),
                ('description', models.TextField(blank=True, help_text='Short description of the food item', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this item is currently available')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in which items appear in the flow')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Food Item',
                'verbose_name_plural': 'Food Items',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Package name (e.g. 'Get a Banner')", max_length=100)),
                ('price', models.DecimalField(decimal_places=2, help_text='Package price in INR', max_digits=10)),
                ('description', models.TextField(blank=True, help_text='Description of what the package includes', null=True)),
                ('category', models.CharField(choices=[('FOOD', 'Food'), ('EDUCATION', 'Education'), ('MEDICAL', 'Medical'), ('ALL', 'All Categories')], default='ALL', help_text='Which donation category this package applies to', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this package is currently available')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Display order in the flow')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Package',
                'verbose_name_plural': 'Packages',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the patient', max_length=100)),
                ('hospital', models.CharField(help_text='Name of the hospital', max_length=200)),
                ('location', models.CharField(help_text='City/town of the hospital', max_length=100)),
                ('goal_amount', models.DecimalField(decimal_places=2, help_text='Total amount needed in INR', max_digits=12)),
                ('raised_amount', models.DecimalField(decimal_places=2, default=0, help_text='Amount raised so far in INR', max_digits=12)),
                ('description', models.TextField(blank=True, help_text='Medical condition / reason for fundraising', null=True)),
                ('photo_url', models.URLField(blank=True, help_text='Photo URL of the patient', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this patient is currently accepting donations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the student', max_length=100)),
                ('age', models.PositiveIntegerField(help_text='Age of the student')),
                ('school', models.CharField(help_text='Name of the school', max_length=200)),
                ('class_name', models.CharField(help_text="Class/Standard (e.g. '8th Standard')", max_length=50)),
                ('location', models.CharField(help_text='City/town of the student', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Additional details about the student', null=True)),
                ('photo_url', models.URLField(blank=True, help_text='Photo URL of the student', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this student is currently accepting donations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='donation',
            name='category',
            field=models.CharField(blank=True, choices=[('FOOD', '🍲 Food Donation'), ('EDUCATION', '📚 Education Support'), ('MEDICAL', '🏥 Medical Assistance')], help_text='Donation category (Food/Education/Medical)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='easebuzz_access_key',
            field=models.CharField(blank=True, help_text='Easebuzz payment access key', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='easebuzz_txnid',
            field=models.CharField(blank=True, db_index=True, help_text='Easebuzz transaction ID', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='instagram_id',
            field=models.CharField(blank=True, help_text='Instagram ID of the donor (optional)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('UPI', 'UPI'), ('EASEBUZZ', 'Easebuzz'), ('RAZORPAY', 'Razorpay'), ('BANK_TRANSFER', 'Bank Transfer')], help_text='Selected payment method', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', '⏳ Pending'), ('INITIATED', '🔄 Payment Initiated'), ('COMPLETED', '✅ Completed'), ('FAILED', '❌ Failed'), ('REFUNDED', '🔄 Refunded')], default='PENDING', help_text='Current payment status', max_length=20),
        ),
        migrations.CreateModel(
            name='DonationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('FOOD', 'Food Item'), ('STUDENT', 'Student Sponsorship'), ('PATIENT', 'Patient Support')], help_text='Type of item', max_length=20)),
                ('item_name', models.CharField(help_text='Name of the item for display', max_length=200)),
                ('item_id', models.PositiveIntegerField(help_text='ID of the related model (FoodItem, Student, Patient)')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Quantity selected')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per unit at time of donation', max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Quantity × unit_price', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donation', models.ForeignKey(help_text='Parent donation', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='whatsapp_app.donation')),
            ],
            options={
                'verbose_name': 'Donation Item',
                'verbose_name_plural': 'Donation Items',
                'ordering': ['item_type', 'item_name'],
            },
        ),
        migrations.CreateModel(
            name='DonationPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(help_text='Package name at time of donation', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, help_text='Package price at time of donation', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donation', models.ForeignKey(help_text='Parent donation', on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='whatsapp_app.donation')),
                ('package', models.ForeignKey(blank=True, help_text='Selected package', null=True, on_delete=django.db.models.deletion.SET_NULL, to='whatsapp_app.package')),
            ],
            options={
                'verbose_name': 'Donation Package',
                'verbose_name_plural': 'Donation Packages',
            },
        ),
        migrations.AddField(
            model_name='donation',
            name='patient',
            field=models.ForeignKey(blank=True, help_text='Linked patient (for medical donations)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='whatsapp_app.patient'),
        ),
        migrations.AddField(
            model_name='donation',
            name='student',
            field=models.ForeignKey(blank=True, help_text='Linked student (for education donations)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='whatsapp_app.student'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['category'], name='whatsapp_ap_categor_e720df_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['easebuzz_txnid'], name='whatsapp_ap_easebuz_fbd1af_idx'),
        ),
    ]
