# Generated by Django 5.2.14 on 2026-06-27 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_app', '0003_add_package_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, help_text='WhatsApp phone number', max_length=20)),
                ('direction', models.CharField(choices=[('IN', 'Incoming'), ('OUT', 'Outgoing')], help_text='IN = user sent, OUT = bot sent', max_length=3)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('button', 'Button Reply'), ('list', 'List Selection'), ('flow', 'Flow Response'), ('interactive', 'Interactive'), ('image', 'Image'), ('system', 'System')], default='text', help_text='Type of message', max_length=20)),
                ('content', models.TextField(help_text='Message body or selection text')),
                ('metadata', models.JSONField(blank=True, help_text='Extra data (button_id, list_id, flow data, etc.)', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the message was sent/received')),
            ],
            options={
                'verbose_name': 'Conversation Message',
                'verbose_name_plural': 'Conversation Messages',
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['phone_number', 'timestamp'], name='whatsapp_ap_phone_n_52aae3_idx')],
            },
        ),
    ]
